### ISSUE TITLE
Redesign of Wallets dialogs

### ISSUE THREAD

**Issue by paulfears** [paulfears/StellarSnap#51]
MM has released a new interface system for Meta-Mask plugins. Redesign wallet pop-ups using this interface.
[https://docs.metamask.io/snaps/features/custom-ui/dialogs/](docs)
Create a New File for each dialog screen.
- Create one that allows users to send stellar tokens

**Comment by od-hunter** [comment]
Hi @paulfears , please can I work on the redesign of the wallet pop-ups? I’m a ui/ux designer and also a blockchain developer. Please give me the opportunity to contribute to this repo.

**Comment by Dprof-in-tech** [comment]
Hello, i am Dprof-in-tech, an experienced Full Stack Blockchain Developer and  I am excited to contribute my skills to this project in this ODHACK 8. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js,  Rust and Cairo, I've honed my technical skills across the blockchain development landscape.

My journey with OnlyDust began at Edition 2, and I've since made 34 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.

My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we begin ODHACK 8, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.

Below is a link to my OnlyDust public profile.
https://app.onlydust.com/u/Dprof-in-tech

HOW I WOULD SOLVE THIS ISSUE

I will research MetaMask’s new interface system:
I will begin by reviewing MetaMask's official documentation and resources regarding the newly released interface for plugins, ensuring I fully understand the changes and new features.
I will gather insights on MetaMask’s design system, best practices for wallet interactions, and any relevant UI/UX guidelines they have provided for developers.
This will help ensure that the redesigned wallet pop-ups align perfectly with MetaMask’s new interface system.

I will analyze the existing wallet dialog components:

Before starting the redesign, I will thoroughly examine the current implementation of wallet dialogs in the project.
I will identify the areas where changes are required to integrate MetaMask’s new interface system, including potential updates to UI components, state management, and wallet connection logic.
I will also evaluate how these dialogs interact with other parts of the application to avoid any breaking changes.

I will map out the new UI flow:
Based on the information gathered from MetaMask’s documentation and the current design, I will create a visual flow of how the new wallet dialogs will behave.
This will include the key states such as wallet connection, approval, confirmation, transaction details, network switching, and errors.
I will sketch or prototype the changes, ensuring that each dialog follows MetaMask’s new UI patterns, including responsiveness and accessibility.

I will update the dialog components according to MetaMask’s new UI:
I will update the wallet pop-up dialogs to adopt the new MetaMask interface, ensuring they reflect the latest design guidelines for consistency and enhanced user experience.

These updates will include:
Visual redesign of the dialogs (modals), following MetaMask’s new aesthetic guidelines.
Updated buttons, input fields, and pop-up elements, ensuring they look and function as required by the new system.
Ensuring that pop-ups are fully responsive, accessible, and look great in both light and dark modes, if applicable.

I will implement the new MetaMask plugin API (if applicable):
If MetaMask’s new interface system includes updates to the API or connection process, I will update the logic accordingly. 
This may involve:
Updating the methods used to request wallet connections, transactions, and approvals.
Ensuring that any interactions with the MetaMask wallet follow the new plugin standards for security, notifications, and confirmation flows.

I will handle error states and provide appropriate user feedback as per MetaMask’s recommendations.

I will ensure a seamless user experience:
I will ensure that the redesigned wallet dialogs maintain a smooth and intuitive experience for users. The flow will be optimized for:
Quick wallet connections, minimizing friction for users during transaction approvals.
Clear and concise error handling, where users are given actionable instructions if something goes wrong during a transaction or wallet interaction.

I will ensure the dialogs reflect the same high-level UX found in MetaMask’s own pop-up windows for consistency.
I will conduct cross-browser and device testing:
I will test the redesigned dialogs across multiple browsers and devices (desktop and mobile) to ensure they function properly in all environments, especially considering MetaMask’s heavy use in decentralized applications across different devices.
I will check for potential performance issues, bugs, or any visual glitches that could arise during wallet interactions.

I will gather feedback and iterate:
After the initial implementation, I will present the redesigned dialogs to the team for feedback. I will make sure to capture any areas of improvement and refine the design based on input from stakeholders.
I will also validate the design and functionality with MetaMask's recommended testing scenarios.

I will document and submit the changes:
Once the redesign is complete and tested, I will document the changes made, including any updates to wallet connection logic, new interface elements, and guidance on how the new dialogs behave.
I will submit a comprehensive pull request with details on how the redesign meets MetaMask’s new interface guidelines and attach screenshots or video demonstrations of the updated dialogs in action.

my estimated time of delievery would be 3 days from the assignment date.

**Comment by od-hunter** [comment]
Hi @paulfears , can I work on this please?

**Comment by StealthCoder1109** [comment]
Hi @paulfears ,

I’m interested in helping you redesign the MetaMask pop-ups using the new Snaps system for sending Stellar tokens. I have experience in both blockchain development and frontend design, so I’m confident I can deliver a user-friendly solution for your project.
My Approach:

    Dialog UI: I’ll create a simple dialog where users can enter the recipient’s Stellar address, token amount, and other details if needed (like memo or transaction fees).

    MetaMask Snaps Integration: The dialog will be integrated with MetaMask’s Snaps, making sure it works smoothly with the new system.

    Testing: I will thoroughly test the solution to ensure it’s secure and functions properly.

Why Me:

    Experience with MetaMask and blockchain projects.
    Strong skills in creating clean, responsive interfaces.
    Focus on delivering high-quality work.

If you’re interested, I’d love to discuss more details. Feel free to reach out with any questions.

Thanks!

**Comment by StealthCoder1109** [comment]
Hi @paulfears,
I’m interested in helping you redesign the MetaMask pop-ups using the new Snaps system for sending Stellar tokens. I have experience in both blockchain development and frontend design, so I’m confident I can deliver a user-friendly solution for your project.
My Approach:
     Dialog UI: I’ll create a simple dialog where users can enter the recipient’s Stellar address, token amount, and other details if needed (like memo or transaction fees).
      MetaMask Snaps Integration: The dialog will be integrated with MetaMask’s Snaps, making sure it works smoothly with the new system.
     Testing: I will thoroughly test the solution to ensure it’s secure and functions properly.
Timeline:

I can complete the project in [insert your estimated time].
Why Me:
    Experience with MetaMask and blockchain projects.
    Strong skills in creating clean, responsive interfaces.
    Focus on delivering high-quality work.
If you’re interested, I’d love to discuss more details. Feel free to reach out with any questions.
Thanks!

**Comment by paulfears** [comment]
Took the liberty of correcting this with latest commit, pm if you want to help refine the new design
